config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }
  resources :products, only: [:show, :index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  root to: "products#index"
 resources :charges
 resources :carts
  


end

app/models/product.rb
class Product < ActiveRecord::Base
 
  has_many :order_items
  
  
  default_scope { where(active: true) }
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 def index
    @products = Product.all
    @order_item = Cart.new
  end

  def show

    @product = Product.find(params[:id])
    @similar_products = Product.select {|product| product.id != @product.id}.slice(0, 3)
  end

  private
    def products_params
      params.permit(:title, :description, :price)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
      <%= link_to "See", product_path(product.id) %>
    </div>
    <div class="col-xs-4">
      
      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            

            

            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
    
  </div>
</div>

app/views/products/index.html.erb
<h3 class="text-center">Products for Sale</h3>

<div class="row">
  <div class="col-xs-6 col-xs-offset-3">
    <% @products.each do |product| %>
      <%= render "product_row", product: product, order_item: @order_item %>
    <% end %>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
    <div class="row single-product">
        <div class="col-md-9">
            <div class="row">
                <div class="col-md-5 margin-b-30">
                    <div class="item">
                        
                    </div>
                </div>
                <div class="col-md-7">
                    <div class="product-detail-desc">
                        <h3 class="title"> Le produit <%= @product.name %></h3>
                        <span class="price"> <%= @product.price %> BTC</span>
                        <span class="price"> <%= @product.id %></span>
                        
                      
                     
                    </div>
                </div>
            </div>
        </div>  